# Generated by Django 3.1.7 on 2023-12-20 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20231220_1627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
