# Generated by Django 3.1.7 on 2023-12-20 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_favoritegallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteGallery',
        ),
    ]
