# Generated by Django 4.2.8 on 2023-12-25 05:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0014_alter_artwork_id_alter_customuser_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_artworks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artwork',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
