# Generated by Django 4.2.8 on 2024-01-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_artwork_image_alter_artwork_title_inboxmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_artistic_value',
            field=models.PositiveIntegerField(default=0, verbose_name='ارزش هنری کل'),
        ),
    ]
