# Generated by Django 4.2.8 on 2024-01-08 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_userprofile_total_artistic_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='total_artistic_value',
        ),
    ]
