# Generated by Django 4.2.8 on 2024-01-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_userprofile_total_artistic_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_artistic_value',
            field=models.PositiveIntegerField(default=0, verbose_name='ارزش هنری کل'),
        ),
    ]
