# Generated by Django 4.2.9 on 2024-01-10 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0019_userprofile_total_artistic_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='current_bid_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ فعلی مزایده'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='current_highest_bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_highest_bidder_artworks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inboxmessage',
            name='related_artwork',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.artwork'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_by_artworks', to=settings.AUTH_USER_MODEL),
        ),
    ]
