# Generated by Django 4.2.9 on 2024-01-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_artwork_current_bid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
